version: '3.8'

services:

  backend:
    image:  huy1412/edtech-be:v3.0.1
    container_name: backend
    ports:
      - "8080:8080"


  frontend:
    image: huy1412/edtech-fe:v3.0.0
    container_name: front

    depends_on:
      - backend
    ports:
      - "80:80"
